spring:
  application:
    name: kubernetes-reload-config
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000
      config:
        sources:
          - name: ${spring.application.name}
server:
  port: 8080

management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true